services:
  - type: web
    name: mellstroy-bot
    runtime: image
    image:
      dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mellstroy-db
          property: connectionString

databases:
  - name: mellstroy-db
    plan: free
